#!/bin/bash

export MOLECULE_IMAGE="geerlingguy/docker-ubuntu2004-ansible"
export MOLECULE_DISTRIBUTION="ubuntu2004"
export MOLECULE_SCENARIO="default"
# https://github.com/ansible/ansible/issues/67004
export ANSIBLE_PIPELINING=false
