---
- name: Get dotfiles_user passwd database record
  getent:
    database: passwd
    key: "{{ dotfiles_user }}"
    split: ":"

- name: Set {{ dotfiles_user }} home
  set_fact:
    dotfiles_user_home: "{{ getent_passwd[dotfiles_user][4] }}"

- name: Define dotfiles_root
  set_fact:
    dotfiles_root: "{{ dotfiles_user_home }}/.config/dotfiles"
  when: dotfiles_root is not defined
