---
- name: dotfiles | Clone dotfiles repo
  git:
    repo: https://github.com/hurricanehrndz/dotfiles.git
    dest: "{{ dotfiles_root }}"
    version: master
  register: dotfiles_git_result
  changed_when: "dotfiles_git_result.after|default('after') != dotfiles_git_result.before|default('before')"

- name: dotfiles | Make needed directories
  file:
    path: "{{ item.dir }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - dir: "~/.config"
      mode: "0700"
    - dir: "~/.ssh"
      mode: "0700"
    - dir: "~/.gnupg"
      mode: "0700"

# clean broken links
- name: dotfiles | Install dotfiles via dotbot
  shell:
    cmd: ./install
    creates: "{{ dotfiles_user_home }}/.config/zsh"
    chdir: "{{ dotfiles_root }}"
  environment:
    HOME: "{{ dotfiles_user_home }}"
