#!/bin/bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker commit ansible-morethandotfiles_ubuntu18 hurricane/morethandotfiles
docker push hurricane/morethandotfiles
