---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: lxd
lint: |
    yamllint .
    ansible-lint .
    ansible-lint molecule/resources/playbooks/converge.yml
    flake8
platforms:
  - name: "morethandotfiles-${MOLECULE_DISTRIBUTION:-ubuntu-focal}"
    alias: "${MOLECULE_IMAGE:-ubuntu/focal}"
provisioner:
  name: ansible
  options:
    vvv: true
  playbooks:
    create: ../resources/playbooks/create.yml
    converge: ../resources/playbooks/converge.yml
    destroy: ../resources/playbooks/destroy.yml
verifier:
  name: testinfra
  directory: ../resources/tests/
  options:
    verbose: true
