---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint .
    ansible-lint molecule/resources/playbooks/converge.yml
    flake8
platforms:
  - name: "ansible-morethandotfiles_${MOLECULE_DISTRIBUTION:-ubuntu18}"
    image: "${MOLECULE_IMAGE:-quay.io/samdoran/ubuntu18-ansible}"
    command: ${MOLECULE_COMMAND:-""}
    dockerfile: ../resources/playbooks/Dockerfile.j2
    tmpfs:
      - /run
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/dev/fuse:/dev/fuse'
      - '/dev/loop-control:/dev/loop-control'
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  options:
    vvv: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
verifier:
  name: testinfra
  directory: ../resources/tests/
  options:
    verbose: true
