---
- name: Converge
  hosts: all
  vars:
    dotfiles_user: hurricanehrndz
  tasks:
    - name: Add test user
      user:
        name: "{{ dotfiles_user }}"
        shell: /bin/zsh
        create_home: yes

    - name: Run role
      include_role:
        name: ansible-morethandotfiles
