---
- name: Converge
  hosts: all
  vars:
    dotfiles_user: hurricanehrndz
  pre_tasks:
    - name: Update repo cache
      action: >
        {{ ansible_pkg_mgr }} update_cache=yes
      changed_when: false
  tasks:
    - name: Add test user
      user:
        name: "{{ dotfiles_user }}"
        shell: /bin/zsh
        create_home: yes

    - name: Include platform specific variables
      include_vars: '{{ item }}'
      with_first_found:
        - '{{ ansible_os_family }}.yml'
        - default.yml

    - name: Run role
      include_role:
        name: morethandotfiles
